# coding=utf-8
# Различные игровые константы (возможно будет разделение на большее
# количество файлов)

# Игровые константы
TOTAL_ENERGY = 100
PLACE_ARMOUR = 1
PLACE_PANTS = 2
PLACE_HAND_WEAPON = 3
PLACE_BELT_WEAPON = 4

# Константы боя
# CT = Cell Type
CT_FLOOR = 1
CT_WALL = 2
CT_DOOR = 3
VISUAL_CELL_HEIGHT = 100.0
VISUAL_CELL_WIDTH = 86.6025404
VISUAL_CELL_RADIUS = 50.0
VIEW_RADIUS = 3
SECONDS_TO_MOVE = 10
ACTION_COST = 1

# Размеры данных
BOOL_SIZE = 1
CHAR_SIZE = 1
SHORT_SIZE = 2
INT_SIZE = 4

# Server side commands ids
S_TRACE = 1
S_LOGIN_FAILURE = 3
S_REGISTER_SUCCESS = 5
S_REGISTER_FAILURE = 7
S_LOGIN_SUCCESS = 9
S_FULL_PARAMS = 11
S_ITEM_INFO = 13
S_SHOP_ITEMS = 15
S_ADD_ITEM = 17
S_CLIENT_MONEY = 19
S_NEW_BID = 21
S_REMOVE_BID = 23
S_UPDATE_BID = 25
S_START_FIGHT_INFO = 27
S_AREA_OPEN = 29
S_KEYS_OPEN = 31
S_CHAT_MESSAGE = 33
S_FINISH_FIGHT = 35
S_YOUR_MOVE = 37
S_MOVE_UNIT = 39
S_UNIT_CHANGE_WEAPON = 41
S_UNIT_ATTACK = 43
S_UNIT_DAMAGE = 45
S_UNIT_ACTION = 47
S_CHANGE_CELL = 49
S_TELEPORT_UNIT = 51
S_KILL_UNIT = 53
S_ADD_UNIT = 55

# Client side commands ids
C_LOGIN = 2
C_REGISTER = 4
C_ITEM_INFO = 6
C_WEAR_ITEM = 8
C_DROP_ITEM = 10
C_BUY_ITEM = 12
C_SELL_ITEM = 14
C_ADD_STAT = 16
C_ENTER_BID = 18
C_EXIT_BID = 20
C_CREATE_BID = 22
C_CHAT_MESSAGE = 24
C_WANT_MOVE = 26
C_CHANGE_WEAPON = 28
C_ATTACK = 30
C_ACTION = 32
